spring.application.name=its

spring.thymeleaf.prefix=file:src/main/resources/templates/

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# connect to h2
#spring.datasource.data-source-class-name=org.h2.Driver
# Optional: keep the database open after the last connection closes
#spring.datasource.url=jdbc:h2:mem:its;DB_CLOSE_DELAY=-1;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.url=jdbc:h2:mem:its;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
#spring.datasource.username=sa
#spring.datasource.password=
#spring.sql.init.encoding=UTF-8 

# Defer script execution until after Hibernate initializes
#spring.jpa.defer-datasource-initialization=true
#spring.datasource.initialize=true 
#spring.sql.init.schema-locations=classpath:schema.sql 
#spring.sql.init.data-locations=classpath:data.sql 

# Ensure the initialization mode is set to always (default for embedded DBs, needed for others). Spring Boot >= 2.5.0
#spring.sql.init.mode=always

# Optional: customize the console URL path
#spring.h2.console.path=/h2-console
#spring.h2.console.enabled=true

# connect to postgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/its?currentSchema=its
spring.datasource.username=uidits
spring.datasource.password=pWd30@Its

mybatis.configuration.map-underscore-to-camel-case=true

# Allow database to create the schema from entities. create or update for existing schemas
#spring.jpa.hibernate.ddl-auto=update
# 実行されるSQLをコンソールに表示する
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


# max file size - default 1MB
spring.servlet.multipart.max-file-size=10MB
# max request size - default 10MB
spring.servlet.multipart.max-request-size=25MB

spring.jpa.open-in-view=false

#spring.devtools.restart.enabled=false # default is true

spring.main.banner-mode=off
#logging.level.root=warn
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=trace
#logging.level.org.springframework.aop=debug
logging.level.org.springframework.context.support=DEBUG


spring.thymeleaf.cache=false
spring.messages.cache-duration=0
# set character encoding for messages
spring.messages.encoding=UTF-8
# set prefix for message files
spring.messages.basename=i18n/messages
# 言語が見つからない場合にデフォルト(messages.properties)を使う
spring.messages.fallback-to-system-locale=true

server.servlet.session.cookie.name=web_service_its
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
# if set true, cookie can only be set when using https
server.servlet.session.cookie.secure=false

# テンプレートの場所（デフォルト: classpath:/templates/）
spring.thymeleaf.prefix=classpath:/templates/
# 拡張子（デフォルト: .html）
spring.thymeleaf.suffix=.html




